[package]
name = 'grilme99/flow'
description = 'https://github.com/grilme99/Flow'
version = '1.0.0'
license = 'MIT'
authors = ['Brooke Rhodes']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
YogaSys = 'grilme99/yoga-sys@1.19.0'
LuauPolyfill = "jsdotlua/luau-polyfill@1.2.3"
