[package]
name = 'grilme99/yoga-sys'
description = 'https://github.com/grilme99/Flow'
version = '1.19.0'
license = 'MIT'
authors = ['Facebook, inc.', 'Roblox Corporation', 'Brooke Rhodes']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
LuauPolyfill = "jsdotlua/luau-polyfill@1.2.3"
