name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Aftman
        uses: ok-nick/setup-aftman@v0

      - name: Install Just
        uses: extractions/setup-just@v1

      - name: Install dependencies
        shell: bash
        run: just install-packages

      - name: Analyze
        shell: bash
        run: just analyze

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Aftman
        uses: ok-nick/setup-aftman@v0

      - name: Lint
        run: |
          selene ./packages

  style:
    name: Styling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check code style
        uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v0.17.1
          args: --check ./packages
