name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Install Aftman
        uses: ok-nick/setup-aftman@v0

      - name: Authenticate Wally
        run: wally login --token ${{ secrets.WALLY_ACCESS_TOKEN }}

      - name: Get latest release
        id: latest-release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true # This will error if no tags have been made yet, in which case publish.sh will fallback.

      - name: Publish changed packages
        run: bash ./scripts/publish.sh ${{ steps.latest-release.outputs.tag_name }}

      - name: Install Just
        uses: extractions/setup-just@v1

      - name: Install dependencies
        shell: bash
        run: just install-packages

      - name: Build project
        run: rojo build build.project.json --output Flow.rbxm

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.WALLY_ACCESS_TOKEN }}
        with:
          name: Release ${{ github.ref }}
          tag: ${{ github.ref }}
          draft: true

      - name: Upload build artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Flow.rbxm
          asset_name: Flow.rbxm
          asset_content_type: application/octet-stream
